<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>true</SelfContained>
		<PublishReadyToRun>true</PublishReadyToRun>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<ApplicationIcon>Assets\avalonia-logo6.ico</ApplicationIcon>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
		<OutputType>Exe</OutputType>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<OutputType>Exe</OutputType>
		<DefineConstants>$(DefineConstants);PUBLISHED</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Einsatzplanung.GUI\Einsatzplanung.GUI.csproj" />
		<ProjectReference Include="..\Einsatzplanung.Util\Einsatzplanung.Util.csproj" />
		<ProjectReference Include="..\Einsatzplanung.Input\Einsatzplanung.Input.csproj" />
		<ProjectReference Include="..\Einsatzplanung.Generation\Einsatzplanung.Generation.csproj" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Assets\**\*" />
	</ItemGroup>

</Project>
